#!/usr/bin/env python

import sys

Import("env")

common_server = [
    "os_server.cpp",
]

if sys.platform == "darwin":
    common_server.append("#platform/osx/crash_handler_osx.mm")
    common_server.append("#platform/osx/power_osx.cpp")
else:
    common_server.append("#platform/x11/crash_handler_x11.cpp")
    common_server.append("#platform/x11/power_x11.cpp")

# remove system libs
godot_libs = [l for l in env['LIBS'] if not isinstance(l, str)]

def merge_libs(env, target, source):
    mri_script = f'create {target[0]}\n'
    for s in source:
        mri_script += f'addlib {s}\n'
    mri_script += 'save\nend'

    with os.popen('ar -M', mode='w') as p:
        p.write(mri_script)
        p.close()

# merge everything together
prog = env.Command(f'#bin/libgodot_server{env["LIBSUFFIX"]}', ["godot_server.cpp"] + common_server + godot_libs, merge_libs)
